#!/usr/bin/env python3
"""
png_to_lvgl.py — PNG'yi LVGL lv_img_dsc_t C array'ine çevir.

Format: RGB565 little-endian (LV_IMG_CF_TRUE_COLOR @ LV_COLOR_DEPTH=16).
Çıktı: const lv_img_dsc_t <var> = { ... };  + raw byte array.

Kullanım:
    python3 tools/png_to_lvgl.py <input.png> <var_name> <output.c>
    python3 tools/png_to_lvgl.py docs/img/bootsplash.png splash_logo \\
            main/splash_logo.c
"""
import sys, struct
from PIL import Image

if len(sys.argv) != 4:
    print(__doc__); sys.exit(1)

PNG, VAR, OUT = sys.argv[1], sys.argv[2], sys.argv[3]

img = Image.open(PNG).convert("RGB")
w, h = img.size
pixels = img.load()

# Pack RGB565 little-endian
data = bytearray()
for y in range(h):
    for x in range(w):
        r, g, b = pixels[x, y]
        r5 = (r >> 3) & 0x1F
        g6 = (g >> 2) & 0x3F
        b5 = (b >> 3) & 0x1F
        rgb565 = (r5 << 11) | (g6 << 5) | b5
        data.extend(struct.pack("<H", rgb565))

with open(OUT, "w") as f:
    f.write(f"/* Auto-generated by tools/png_to_lvgl.py from {PNG} */\n")
    f.write(f"/* {w}x{h} RGB565, {len(data)} bytes */\n")
    f.write('#include "lvgl.h"\n\n')
    f.write(f"static const uint8_t {VAR}_data[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        line = ", ".join(f"0x{b:02x}" for b in chunk)
        f.write(f"    {line},\n")
    f.write("};\n\n")
    f.write(f"const lv_img_dsc_t {VAR} = {{\n")
    f.write(f"    .header.cf          = LV_IMG_CF_TRUE_COLOR,\n")
    f.write(f"    .header.always_zero = 0,\n")
    f.write(f"    .header.reserved    = 0,\n")
    f.write(f"    .header.w           = {w},\n")
    f.write(f"    .header.h           = {h},\n")
    f.write(f"    .data_size          = {len(data)},\n")
    f.write(f"    .data               = {VAR}_data,\n")
    f.write(f"}};\n")

print(f"wrote {OUT} ({len(data)} bytes RGB565, {w}x{h})")
